### ISSUE TITLE
wrong Dead code elimination results

### ISSUE THREAD

**Issue by 0xhicham** [JonathanSalwan/Triton#1178]
While trying to simplify this bloc of hell it ended up generating wrong results : probably the idea isn't ready yet to deal with hardcore MBAs.

**Instruction(b"\x48\x8D\x1D\x5F\x46\x63\xFE"),
Instruction(b"\x53"),
Instruction(b"\x48\x63\x1D\xF2\xAE\xEC\xFA"),
Instruction(b"\x49\x09\xCA"),
Instruction(b"\x48\x01\x1C\x24"),
Instruction(b"\x4C\x8D\x15\x10\x61\x83\xF4"),
Instruction(b"\x5B"),
Instruction(b"\x4C\x8D\x15\x58\x0F\x16\xFE"),
Instruction(b"\x41\x52"),
Instruction(b"\x4C\x63\x15\x00\x5B\xC5\xFC"),
Instruction(b"\x4C\x01\x14\x24"),
Instruction(b"\x41\x5A"),
Instruction(b"\x53"),
Instruction(b"\x4C\x0F\x44\xD1"),
Instruction(b"\x48\x8D\x1D\x53\xA1\xFD\xFB"),
Instruction(b"\x53"),
Instruction(b"\x48\x63\x1D\xC7\x93\xCE\xFE"),
Instruction(b"\x48\x01\x1C\x24"),
Instruction(b"\x5B"),
Instruction(b"\x8B\x1B"),
Instruction(b"\x48\xC1\xE3\x20"),
Instruction(b"\x48\xC1\xFB\x20"),
Instruction(b"\x48\xF7\x1C\x24"),
Instruction(b"\x48\x29\x1C\x24"),
Instruction(b"\x49\xC1\xEA\x24"),
Instruction(b"\x48\xF7\x1C\x24"),
Instruction(b"\x5B"),
Instruction(b"\x4C\x0F\xB7\x12"),
Instruction(b"\x48\x8D\x64\x24\xF8"),
Instruction(b"\x4C\x89\x2C\x24"),
Instruction(b"\x4D\x31\xED"),
Instruction(b"\x49\x09\xC5"),
Instruction(b"\x49\x21\xC5"),
Instruction(b"\x48\x09\xC0"),
Instruction(b"\x4C\x29\xE8"),
Instruction(b"\x4C\x8B\x2C\x24"),
Instruction(b"\x4C\x89\x14\x24"),
Instruction(b"\x49\xC1\xC2\x31"),
Instruction(b"\x41\x5A"),
Instruction(b"\x66\x0F\x42\x81\x18\x03\x00\x00"),
Instruction(b"\x48\x8D\x64\x24\xF8"),
Instruction(b"\x48\x89\x3C\x24"),
Instruction(b"\x55"),
Instruction(b"\x48\x8D\x64\x24\xF8"),
Instruction(b"\x4C\x89\x3C\x24"),
Instruction(b"\x41\xFF\xCF"),
Instruction(b"\x41\x89\xEF"),
Instruction(b"\x57"),
Instruction(b"\xF7\xDD"),
Instruction(b"\x81\xED\x11\x03\x0C\x31"),
Instruction(b"\x41\x01\xEF"),
Instruction(b"\xBD\x5E\x38\x00\x2A"),
Instruction(b"\x89\xEF"),
Instruction(b"\x41\x29\xFF"),
Instruction(b"\x5F"),
Instruction(b"\x44\x21\xFD"),
Instruction(b"\xC1\xC5\x04"),
Instruction(b"\x53"),
Instruction(b"\x89\xEB"),
Instruction(b"\x44\x29\xFB"),
Instruction(b"\xF7\xDB"),
Instruction(b"\x41\x89\xDF"),
Instruction(b"\x5B"),
Instruction(b"\x44\x0F\xA4\xFD\x06"),
Instruction(b"\xC1\xD5\x19"),
Instruction(b"\x89\xD5"),
Instruction(b"\x41\x5F"),
Instruction(b"\x5D"),
Instruction(b"\x41\x55"),
Instruction(b"\x66\x44\x89\xD7"),
Instruction(b"\x66\x45\x89\xD5"),
Instruction(b"\x66\x41\xBA\xFF\x7F"),
Instruction(b"\x66\x45\x09\xEA"),
Instruction(b"\x66\x81\xF7\xFF\x00"),
Instruction(b"\x66\x83\xF7\x00"),
Instruction(b"\x66\x81\xF7\x00\x7F"),
Instruction(b"\x66\x45\x31\xED"),
Instruction(b"\x66\x41\x01\xFD"),
Instruction(b"\x66\x44\x89\xD7"),
Instruction(b"\x50"),
Instruction(b"\x52"),
Instruction(b"\x4C\x89\xE8"),
Instruction(b"\x48\xC7\xC2\x00\x20\x00\x00"),
Instruction(b"\x48\xF7\xE2"),
Instruction(b"\x66\x44\x89\xEF"),
Instruction(b"\x5A"),
Instruction(b"\x66\x41\x01\xFA"),
Instruction(b"\x66\x44\x01\xEF"),
Instruction(b"\x49\x89\xC5"),
Instruction(b"\x66\x41\x29\xFA"),
Instruction(b"\x58"),
Instruction(b"\x4C\x8B\x2C\x24"),
Instruction(b"\x83\xCF\x5A"),
Instruction(b"\x48\x8D\x64\x24\x08"),
Instruction(b"\x48\x8B\x3C\x24"),
Instruction(b"\x48\x8D\x64\x24\xF8"),
Instruction(b"\x48\x89\x1C\x24"),
Instruction(b"\x48\x83\xEC\x08"),
Instruction(b"\x4C\x89\x34\x24"),
Instruction(b"\x55"),
Instruction(b"\x56"),
Instruction(b"\xBD\x51\x88\x48\x57"),
Instruction(b"\xBE\xCD\x24\xAC\xCF"),
Instruction(b"\x01\xF5"),
Instruction(b"\x89\xEE"),
Instruction(b"\x89\xD5"),
Instruction(b"\x41\xBE\xDD\x27\xCA\x42"),
Instruction(b"\x41\xC1\xCE\x08"),
Instruction(b"\x41\x56"),
Instruction(b"\x44\x89\xF5"),
Instruction(b"\x41\x81\xF6\xED\x0B\x12\xDC"),
Instruction(b"\x44\x31\xF5"),
Instruction(b"\x81\xF6\x6F\x7C\x81\xA8"),
Instruction(b"\x21\xEE"),
Instruction(b"\xC1\xC5\x19"),
Instruction(b"\x81\xDD\xAE\xAA\x8C\x8C"),
Instruction(b"\xBB\xDD\x4A\x97\x4E"),
Instruction(b"\x41\x5E"),
Instruction(b"\x19\xF5"),
Instruction(b"\x81\xCD\x6E\xD6\x14\x58"),
Instruction(b"\x48\x63\xDB"),
Instruction(b"\x48\xC1\xDB\x11"),
Instruction(b"\x89\xDB"),
Instruction(b"\xC1\xC3\x1C"),
Instruction(b"\x44\x21\xF3"),
Instruction(b"\x48\x8B\x34\x24"),
Instruction(b"\x48\x8D\x64\x24\x08"),
Instruction(b"\x5D"),
Instruction(b"\x41\x11\xDE"),
Instruction(b"\xFF\xC3"),
Instruction(b"\x4C\x8B\x34\x24"),
Instruction(b"\x48\x83\xC4\x08"),
Instruction(b"\x5B"),
Instruction(b"\x4C\x89\x1C\x24"),
Instruction(b"\x41\x51"),
Instruction(b"\x41\x57"),
Instruction(b"\x66\x45\x89\xD3"),
Instruction(b"\x66\x45\x89\xD7"),
Instruction(b"\x66\x41\x21\xC2"),
Instruction(b"\x66\x41\x31\xC7"),
Instruction(b"\x66\x45\x01\xFA"),
Instruction(b"\x41\x5F"),
Instruction(b"\x50"),
Instruction(b"\x48\x8D\x64\x24\xF8"),
Instruction(b"\x4C\x89\x14\x24"),
Instruction(b"\x52"),
Instruction(b"\x45\x31\xD2"),
Instruction(b"\x41\x81\xC2\x6A\xD4\x32\x74"),
Instruction(b"\xB8\x13\x5F\xE4\xD4"),
Instruction(b"\x41\x81\xEA\xF6\x18\x7A\x85"),
Instruction(b"\x44\x01\xD0"),
Instruction(b"\x53"),
Instruction(b"\x15\xFA\x6A\x96\xE3"),
Instruction(b"\x48\x8D\x15\x6C\xE6\x33\xF7"),
Instruction(b"\x29\xD2"),
Instruction(b"\x44\x09\xD2"),
Instruction(b"\x49\x81\xDA\xF3\xFF\xFF\xFF"),
Instruction(b"\x41\x89\xDA"),
Instruction(b"\x66\x45\x89\xD9"),
Instruction(b"\xF7\xDB"),
Instruction(b"\x81\xEB\x70\xAA\xFB\x93"),
Instruction(b"\x41\x01\xDA"),
Instruction(b"\x5B"),
Instruction(b"\x41\x09\xD2"),
Instruction(b"\x48\x8D\x15\x53\xE1\x33\xF7"),
Instruction(b"\x48\x8B\x14\x24"),
Instruction(b"\x41\x21\xC2"),
Instruction(b"\x48\x8D\x64\x24\x08"),
Instruction(b"\x48\x98"),
Instruction(b"\x4C\x8B\x14\x24"),
Instruction(b"\x48\x8D\x64\x24\x08"),
Instruction(b"\x48\x8B\x04\x24"),
Instruction(b"\x66\x41\x09\xC3"),
Instruction(b"\x66\x41\x31\xC1"),
Instruction(b"\x66\x45\x29\xCB"),
Instruction(b"\x66\x41\x01\xC2"),
Instruction(b"\x66\x44\x01\xD8"),
Instruction(b"\x48\x83\xC4\x08"),
Instruction(b"\x66\x41\x29\xC2"),
Instruction(b"\x41\x59"),
Instruction(b"\x4C\x8B\x1C\x24"),
Instruction(b"\x48\x8D\x64\x24\x08"),
Instruction(b"\x8B\x05\xF7\x6E\x33\xF7"),
Instruction(b"\x48\x83\xEC\x08"),
Instruction(b"\x48\x89\x1C\x24"),
Instruction(b"\x48\x31\xC0"),
Instruction(b"\x48\x89\xC3"),
Instruction(b"\x48\x21\xD3"),
Instruction(b"\x48\x09\xD0"),
Instruction(b"\x48\x89\xDA"),
Instruction(b"\x48\x89\xC3"),
Instruction(b"\x48\x29\xD0"),
Instruction(b"\x48\x8D\x50\x02"),
Instruction(b"\x48\xC7\xC0\x00\x00\x00\x00"),
Instruction(b"\x4A\x8D\x04\x90"),
Instruction(b"\x45\x31\xD2"),
Instruction(b"\x48\x8B\x1C\x24"),
Instruction(b"\x49\x89\xDA"),
Instruction(b"\x49\xF7\xDA"),
Instruction(b"\x49\x29\xC2"),
Instruction(b"\x48\xC7\xC0\x00\x00\x00\x00"),
Instruction(b"\x48\x83\xC4\x08"),
Instruction(b"\x4C\x29\xD0"),
Instruction(b"\x44\x8B\x10"),
Instruction(b"\x41\x53"),
Instruction(b"\x49\x89\xE3"),
Instruction(b"\x9C"),
Instruction(b"\x49\x83\xC3\x00"),
Instruction(b"\x9D"),
Instruction(b"\x4C\x87\x1C\x24"),
Instruction(b"\x5C"),
Instruction(b"\x48\x8D\x05\xE9\x35\x96\xFE"),
Instruction(b"\x48\x89\x04\x24"),
Instruction(b"\x8B\x05\xE4\xD6\x35\xFD"),
Instruction(b"\x48\xC1\xE0\x20"),
Instruction(b"\x53"),
Instruction(b"\x48\xF7\xDB"),
Instruction(b"\x48\x8D\x1D\x6E\xEB\x95\xF9"),
Instruction(b"\x5B"),
Instruction(b"\x48\xC1\xF8\x20"),
Instruction(b"\x48\x01\x04\x24"),
Instruction(b"\x48\x8D\x05\xD4\x8C\x93\xFA"),
Instruction(b"\x48\x8D\x64\x24\xF8"),
Instruction(b"\x4C\x89\x2C\x24"),
Instruction(b"\x4D\x31\xED"),
Instruction(b"\x52"),
Instruction(b"\x49\x31\xC5"),
Instruction(b"\xFF\xC8"),
Instruction(b"\x41\x52"),
Instruction(b"\x4C\x89\xD0"),
Instruction(b"\x48\xBA\x00\x00\x00\x00\x01\x00\x00\x00"),
Instruction(b"\x48\xF7\xE2"),
Instruction(b"\x48\x8D\x15\x85\x17\xCB\xFD"),
Instruction(b"\x49\x89\xD2"),
Instruction(b"\x0F\xBA\xEA\x18"),
Instruction(b"\x4C\x87\x14\x24"),
Instruction(b"\x48\x83\xC4\x08"),
Instruction(b"\x49\x89\xC2"),
Instruction(b"\x48\x8B\x14\x24"),
Instruction(b"\x48\x0F\xAB\xF8"),
Instruction(b"\x49\xC1\xFA\x20"),
Instruction(b"\x0F\xBA\xE8\x0D"),
Instruction(b"\x48\x83\xC4\x08"),
Instruction(b"\x4C\x87\x2C\x24"),
Instruction(b"\x48\x83\xC4\x08"),
Instruction(b"\x48\x8D\x04\x24"),
Instruction(b"\x48\x8B\x00"),
Instruction(b"\x48\x89\x3C\x24"),
Instruction(b"\x48\x81\xEF\xC3\xFF\xFF\xFF"),
Instruction(b"\x48\xFF\xCF"),
Instruction(b"\x49\x01\xC2"),
Instruction(b"\x49\x8D\x3A"),
Instruction(b"\x9C"),
Instruction(b"\x48\x31\x7C\x24\x08"),
Instruction(b"\x48\x33\x7C\x24\x08"),
Instruction(b"\x48\x31\x7C\x24\x08"),
Instruction(b"\x9D"),
Instruction(b"\xC3"),**

**Comment by mrexodia** [comment]
Based Denuvo enjoyer?

**Comment by 0xhicham** [comment]
> Based Denuvo enjoyer?

coming from a denuvo employe not surprised by the comment fam.

**Comment by mrexodia** [comment]
Not anymore fam 😉

**Comment by JonathanSalwan** [comment]
Can you point me what is false in the result?

**Comment by JonathanSalwan** [comment]
Btw, we fixed some bugs few days ago (#1174). Are you up-to-date on `dev-v1.0`?

**Comment by unknown-re** [comment]
still not fixing the issue here is a smaller example :

```asm
lea rbx,qword ptr ds:[149E5B666]
push rbx
push rbx
movsxd rbx,dword ptr ds:[1466F1F01]
or r10,rcx
add qword ptr ss:[rsp],rbx
lea r10,qword ptr ds:[14005D12D]
pop rbx
lea r10,qword ptr ds:[149987F7D]
push r10
movsxd r10,dword ptr ds:[14847CB2E]
add qword ptr ss:[rsp],r10
pop r10
push rbx
cmove r10,rcx
lea rbx,qword ptr ds:[147801193]
push rbx
movsxd rbx,dword ptr ds:[14A51040F]
add qword ptr ss:[rsp],rbx
pop rbx
mov ebx,dword ptr ds:[rbx] 
```
is simplified into : 
```asm
lea rbx, [rip - 0x19cb9a1]
push rbx
movsxd rbx, dword ptr [rip - 0x513510e]
add qword ptr [rsp], rbx
pop rbx
lea r10, [rip - 0x1e9f0a8]
push r10
movsxd r10, dword ptr [rip - 0x33aa500]
add qword ptr [rsp], r10
pop r10
push rbx
cmove r10, rcx
lea rbx, [rip - 0x4025ead]
push rbx
movsxd rbx, dword ptr [rip - 0x1316c39]
add qword ptr [rsp], rbx ;
pop rbx ;
mov ebx, dword ptr [rbx]
```
ending up in a wrong rbx address.

try to check it via symb exec results aren't similar.

**Comment by Hykni** [comment]
The above isn't reproducible for me on the latest changes.

```asm
0x0:  lea rbx, [rip - 0x19cb9a1]
0x7:  push rbx
0x8:  push rbx
0x9:  movsxd rbx, dword ptr [rip - 0x513510e]
0x10: or r10, rcx
0x13: add qword ptr [rsp], rbx
0x17: lea r10, [rip - 0x1e9f0a8]
0x1e: pop rbx
0x1f: lea r10, [rip - 0x1e9f0a8]
0x26: push r10
0x28: movsxd r10, dword ptr [rip - 0x33aa500]
0x2f: add qword ptr [rsp], r10
0x33: pop r10
0x35: push rbx
0x36: cmove r10, rcx
0x3a: lea rbx, [rip - 0x4025ead]
0x41: push rbx
0x42: movsxd rbx, dword ptr [rip - 0x1316c39]
0x49: add qword ptr [rsp], rbx
0x4d: pop rbx
0x4e: mov ebx, dword ptr [rbx]
```
simplifies into
```asm
0x0:  lea rbx, [rip - 0x19cb9a1]
0x7:  push rbx
0x8:  push rbx
0x9:  movsxd rbx, dword ptr [rip - 0x513510e]
0x10: add qword ptr [rsp], rbx
0x14: pop rbx
0x15: lea r10, [rip - 0x1e9f0a8]
0x1c: push r10
0x1e: movsxd r10, dword ptr [rip - 0x33aa500]
0x25: add qword ptr [rsp], r10
0x29: pop r10
0x2b: push rbx
0x2c: cmove r10, rcx
0x30: lea rbx, [rip - 0x4025ead]
0x37: push rbx
0x38: movsxd rbx, dword ptr [rip - 0x1316c39]
0x3f: add qword ptr [rsp], rbx
0x43: pop rbx
0x44: mov ebx, dword ptr [rbx]
```

Only the dead r10 stores get simplified away.

Here's what I assembled it from:
```cpp
BasicBlock dvBlock({
		Instruction("\x48\x8d\x1d\x5f\x46\x63\xfe", 16),
		Instruction("\x53", 16),
		Instruction("\x53", 16),
		Instruction("\x48\x63\x1d\xf2\xae\xec\xfa", 16),
		Instruction("\x49\x09\xca", 16),
		Instruction("\x48\x01\x1c\x24", 16),
		Instruction("\x4c\x8d\x15\x58\x0f\x16\xfe", 16),
		Instruction("\x5b", 16),
		Instruction("\x4c\x8d\x15\x58\x0f\x16\xfe", 16),
		Instruction("\x41\x52", 16),
		Instruction("\x4c\x63\x15\x00\x5b\xc5\xfc", 16),
		Instruction("\x4c\x01\x14\x24", 16),
		Instruction("\x41\x5a", 16),
		Instruction("\x53", 16),
		Instruction("\x4c\x0f\x44\xd1", 16),
		Instruction("\x48\x8d\x1d\x53\xa1\xfd\xfb", 16),
		Instruction("\x53", 16),
		Instruction("\x48\x63\x1d\xc7\x93\xce\xfe", 16),
		Instruction("\x48\x01\x1c\x24", 16),
		Instruction("\x5b", 16),
		Instruction("\x8b\x1b", 16) });
```

**Comment by unknown-re** [comment]
try with the whole block then check the rbx that i mentioned

**Comment by Hykni** [comment]
The result was with a simplify call on the whole block that you mentioned

**Comment by unknown-re** [comment]
I am on the most recent one dlded via the artefact.
i can 100% confirm that the simplification is fucked up hence i hooked the simplified block & once executed it keeps C5ing on this rbx access , as mrexodia commented (and removed it lol) this piece of code comes from denuvo. probably the mbas there are not that simple.

**Comment by JonathanSalwan** [comment]
I will deep into your example this week.

**Comment by JonathanSalwan** [comment]
On the first block you pasted (https://github.com/JonathanSalwan/Triton/issues/1178#issue-1361203270), there is no two consecutive `push rbx` instructions. But in the comment https://github.com/JonathanSalwan/Triton/issues/1178#issuecomment-1238106395 you refer to an original code with two consecutive `push rbx`. What code is correct?

**Comment by unknown-re** [comment]
here is another example of an actual dispatcher https://pastebin.com/raw/nNTLZ5CV (i wont expose the version for the known reasons) , the simplification goes wrong resulting in a wrong mem access

**Comment by unknown-re** [comment]
just tested in a realtime execution context :
only registers affected are :
**rax , rsp , r9 , r11**
so your results are incorrects.

**Comment by JonathanSalwan** [comment]
> only registers affected are : rax , rsp , r9 , r11

This is weird. Below the script I used. Is your result deterministic?

```python
from triton import *

def sym_mem(ctx, mem):
    addr = mem.getAddress()
    size = mem.getSize()

    if ctx.isMemorySymbolized(mem) == False:
        print(f'Sym memory: {mem}')
        ctx.symbolizeMemory(mem, f's_[{addr:x}:{size}]')

    return


ctx = TritonContext(ARCH.X86_64)
ctx.setConcreteRegisterValue(ctx.registers.rdx, 0xdddd000000000000) # rdx value (defined outside of the basic block)
ctx.setConcreteRegisterValue(ctx.registers.rcx, 0xeeee000000000000) # rcx value (defined outside of the basic block)
ctx.setConcreteRegisterValue(ctx.registers.rsp, 0x5555fffffffffff0) # base stack
ctx.setConcreteRegisterValue(ctx.registers.rbp, 0x5555fffffffffff0) # base stack
ctx.setConcreteRegisterValue(ctx.registers.rip, 0xaaaa000000000000) # base code

ctx.setMode(MODE.ALIGNED_MEMORY, True)
ctx.setMode(MODE.AST_OPTIMIZATIONS, True)
ctx.addCallback(CALLBACK.GET_CONCRETE_MEMORY_VALUE, sym_mem)

ctx.symbolizeRegister(ctx.registers.rax, 's_rax')
ctx.symbolizeRegister(ctx.registers.rbx, 's_rbx')
ctx.symbolizeRegister(ctx.registers.rcx, 's_rcx')
ctx.symbolizeRegister(ctx.registers.rdx, 's_rdx')
ctx.symbolizeRegister(ctx.registers.rdi, 's_rdi')
ctx.symbolizeRegister(ctx.registers.rsi, 's_rsi')
ctx.symbolizeRegister(ctx.registers.rsp, 's_rsp')
ctx.symbolizeRegister(ctx.registers.rbp, 's_rbp')
ctx.symbolizeRegister(ctx.registers.r8,  's_r8')
ctx.symbolizeRegister(ctx.registers.r9,  's_r9')
ctx.symbolizeRegister(ctx.registers.r10, 's_r10')
ctx.symbolizeRegister(ctx.registers.r11, 's_r11')
ctx.symbolizeRegister(ctx.registers.r12, 's_r12')
ctx.symbolizeRegister(ctx.registers.r13, 's_r13')
ctx.symbolizeRegister(ctx.registers.r14, 's_r14')
ctx.symbolizeRegister(ctx.registers.r15, 's_r15')

#
# rax = [rip + 0x2ca2621] + [rsp - 8]
# rbx = [rip + 0x51350ff] + [rsp - 8] + [rip + 0x4025e6d]
# rdx = rdx + 2
# r10 = [rip + 0x19cb99a] + [rsp - 8] + [rip + 0x2ca2621]
#
block = BasicBlock([
    Instruction(b"\x48\x8D\x1D\x5F\x46\x63\xFE"),                       # 0x0: lea rbx, [rip - 0x19cb9a1]
    Instruction(b"\x53"),                                               # 0x7: push rbx
    Instruction(b"\x48\x63\x1D\xF2\xAE\xEC\xFA"),                       # 0x8: movsxd rbx, dword ptr [rip - 0x513510e]
    Instruction(b"\x49\x09\xCA"),                                       # 0xf: or r10, rcx
    Instruction(b"\x48\x01\x1C\x24"),                                   # 0x12: add qword ptr [rsp], rbx
    Instruction(b"\x4C\x8D\x15\x10\x61\x83\xF4"),                       # 0x16: lea r10, [rip - 0xb7c9ef0]
    Instruction(b"\x5B"),                                               # 0x1d: pop rbx
    Instruction(b"\x4C\x8D\x15\x58\x0F\x16\xFE"),                       # 0x1e: lea r10, [rip - 0x1e9f0a8]
    Instruction(b"\x41\x52"),                                           # 0x25: push r10
    Instruction(b"\x4C\x63\x15\x00\x5B\xC5\xFC"),                       # 0x27: movsxd r10, dword ptr [rip - 0x33aa500]
    Instruction(b"\x4C\x01\x14\x24"),                                   # 0x2e: add qword ptr [rsp], r10
    Instruction(b"\x41\x5A"),                                           # 0x32: pop r10
    Instruction(b"\x53"),                                               # 0x34: push rbx
    Instruction(b"\x4C\x0F\x44\xD1"),                                   # 0x35: cmove r10, rcx
    Instruction(b"\x48\x8D\x1D\x53\xA1\xFD\xFB"),                       # 0x39: lea rbx, [rip - 0x4025ead]
    Instruction(b"\x53"),                                               # 0x40: push rbx
    Instruction(b"\x48\x63\x1D\xC7\x93\xCE\xFE"),                       # 0x41: movsxd rbx, dword ptr [rip - 0x1316c39]
    Instruction(b"\x48\x01\x1C\x24"),                                   # 0x48: add qword ptr [rsp], rbx
    Instruction(b"\x5B"),                                               # 0x4c: pop rbx
    Instruction(b"\x8B\x1B"),                                           # 0x4d: mov ebx, dword ptr [rbx]
    Instruction(b"\x48\xC1\xE3\x20"),                                   # 0x4f: shl rbx, 0x20
    Instruction(b"\x48\xC1\xFB\x20"),                                   # 0x53: sar rbx, 0x20
    Instruction(b"\x48\xF7\x1C\x24"),                                   # 0x57: neg qword ptr [rsp]
    Instruction(b"\x48\x29\x1C\x24"),                                   # 0x5b: sub qword ptr [rsp], rbx
    Instruction(b"\x49\xC1\xEA\x24"),                                   # 0x5f: shr r10, 0x24
    Instruction(b"\x48\xF7\x1C\x24"),                                   # 0x63: neg qword ptr [rsp]
    Instruction(b"\x5B"),                                               # 0x67: pop rbx
    Instruction(b"\x4C\x0F\xB7\x12"),                                   # 0x68: movzx r10, word ptr [rdx]
    Instruction(b"\x48\x8D\x64\x24\xF8"),                               # 0x6c: lea rsp, [rsp - 8]
    Instruction(b"\x4C\x89\x2C\x24"),                                   # 0x71: mov qword ptr [rsp], r13
    Instruction(b"\x4D\x31\xED"),                                       # 0x75: xor r13, r13
    Instruction(b"\x49\x09\xC5"),                                       # 0x78: or r13, rax
    Instruction(b"\x49\x21\xC5"),                                       # 0x7b: and r13, rax
    Instruction(b"\x48\x09\xC0"),                                       # 0x7e: or rax, rax
    Instruction(b"\x4C\x29\xE8"),                                       # 0x81: sub rax, r13
    Instruction(b"\x4C\x8B\x2C\x24"),                                   # 0x84: mov r13, qword ptr [rsp]
    Instruction(b"\x4C\x89\x14\x24"),                                   # 0x88: mov qword ptr [rsp], r10
    Instruction(b"\x49\xC1\xC2\x31"),                                   # 0x8c: rol r10, 0x31
    Instruction(b"\x41\x5A"),                                           # 0x90: pop r10
    Instruction(b"\x66\x0F\x42\x81\x18\x03\x00\x00"),                   # 0x92: cmovb ax, word ptr [rcx + 0x318]
    Instruction(b"\x48\x8D\x64\x24\xF8"),                               # 0x9a: lea rsp, [rsp - 8]
    Instruction(b"\x48\x89\x3C\x24"),                                   # 0x9f: mov qword ptr [rsp], rdi
    Instruction(b"\x55"),                                               # 0xa3: push rbp
    Instruction(b"\x48\x8D\x64\x24\xF8"),                               # 0xa4: lea rsp, [rsp - 8]
    Instruction(b"\x4C\x89\x3C\x24"),                                   # 0xa9: mov qword ptr [rsp], r15
    Instruction(b"\x41\xFF\xCF"),                                       # 0xad: dec r15d
    Instruction(b"\x41\x89\xEF"),                                       # 0xb0: mov r15d, ebp
    Instruction(b"\x57"),                                               # 0xb3: push rdi
    Instruction(b"\xF7\xDD"),                                           # 0xb4: neg ebp
    Instruction(b"\x81\xED\x11\x03\x0C\x31"),                           # 0xb6: sub ebp, 0x310c0311
    Instruction(b"\x41\x01\xEF"),                                       # 0xbc: add r15d, ebp
    Instruction(b"\xBD\x5E\x38\x00\x2A"),                               # 0xbf: mov ebp, 0x2a00385e
    Instruction(b"\x89\xEF"),                                           # 0xc4: mov edi, ebp
    Instruction(b"\x41\x29\xFF"),                                       # 0xc6: sub r15d, edi
    Instruction(b"\x5F"),                                               # 0xc9: pop rdi
    Instruction(b"\x44\x21\xFD"),                                       # 0xca: and ebp, r15d
    Instruction(b"\xC1\xC5\x04"),                                       # 0xcd: rol ebp, 4
    Instruction(b"\x53"),                                               # 0xd0: push rbx
    Instruction(b"\x89\xEB"),                                           # 0xd1: mov ebx, ebp
    Instruction(b"\x44\x29\xFB"),                                       # 0xd3: sub ebx, r15d
    Instruction(b"\xF7\xDB"),                                           # 0xd6: neg ebx
    Instruction(b"\x41\x89\xDF"),                                       # 0xd8: mov r15d, ebx
    Instruction(b"\x5B"),                                               # 0xdb: pop rbx
    Instruction(b"\x44\x0F\xA4\xFD\x06"),                               # 0xdc: shld ebp, r15d, 6
    Instruction(b"\xC1\xD5\x19"),                                       # 0xe1: rcl ebp, 0x19
    Instruction(b"\x89\xD5"),                                           # 0xe4: mov ebp, edx
    Instruction(b"\x41\x5F"),                                           # 0xe6: pop r15
    Instruction(b"\x5D"),                                               # 0xe8: pop rbp
    Instruction(b"\x41\x55"),                                           # 0xe9: push r13
    Instruction(b"\x66\x44\x89\xD7"),                                   # 0xeb: mov di, r10w
    Instruction(b"\x66\x45\x89\xD5"),                                   # 0xef: mov r13w, r10w
    Instruction(b"\x66\x41\xBA\xFF\x7F"),                               # 0xf3: mov r10w, 0x7fff
    Instruction(b"\x66\x45\x09\xEA"),                                   # 0xf8: or r10w, r13w
    Instruction(b"\x66\x81\xF7\xFF\x00"),                               # 0xfc: xor di, 0xff
    Instruction(b"\x66\x83\xF7\x00"),                                   # 0x101: xor di, 0
    Instruction(b"\x66\x81\xF7\x00\x7F"),                               # 0x105: xor di, 0x7f00
    Instruction(b"\x66\x45\x31\xED"),                                   # 0x10a: xor r13w, r13w
    Instruction(b"\x66\x41\x01\xFD"),                                   # 0x10e: add r13w, di
    Instruction(b"\x66\x44\x89\xD7"),                                   # 0x112: mov di, r10w
    Instruction(b"\x50"),                                               # 0x116: push rax
    Instruction(b"\x52"),                                               # 0x117: push rdx
    Instruction(b"\x4C\x89\xE8"),                                       # 0x118: mov rax, r13
    Instruction(b"\x48\xC7\xC2\x00\x20\x00\x00"),                       # 0x11b: mov rdx, 0x2000
    Instruction(b"\x48\xF7\xE2"),                                       # 0x122: mul rdx
    Instruction(b"\x66\x44\x89\xEF"),                                   # 0x125: mov di, r13w
    Instruction(b"\x5A"),                                               # 0x129: pop rdx
    Instruction(b"\x66\x41\x01\xFA"),                                   # 0x12a: add r10w, di
    Instruction(b"\x66\x44\x01\xEF"),                                   # 0x12e: add di, r13w
    Instruction(b"\x49\x89\xC5"),                                       # 0x132: mov r13, rax
    Instruction(b"\x66\x41\x29\xFA"),                                   # 0x135: sub r10w, di
    Instruction(b"\x58"),                                               # 0x139: pop rax
    Instruction(b"\x4C\x8B\x2C\x24"),                                   # 0x13a: mov r13, qword ptr [rsp]
    Instruction(b"\x83\xCF\x5A"),                                       # 0x13e: or edi, 0x5a
    Instruction(b"\x48\x8D\x64\x24\x08"),                               # 0x141: lea rsp, [rsp + 8]
    Instruction(b"\x48\x8B\x3C\x24"),                                   # 0x146: mov rdi, qword ptr [rsp]
    Instruction(b"\x48\x8D\x64\x24\xF8"),                               # 0x14a: lea rsp, [rsp - 8]
    Instruction(b"\x48\x89\x1C\x24"),                                   # 0x14f: mov qword ptr [rsp], rbx
    Instruction(b"\x48\x83\xEC\x08"),                                   # 0x153: sub rsp, 8
    Instruction(b"\x4C\x89\x34\x24"),                                   # 0x157: mov qword ptr [rsp], r14
    Instruction(b"\x55"),                                               # 0x15b: push rbp
    Instruction(b"\x56"),                                               # 0x15c: push rsi
    Instruction(b"\xBD\x51\x88\x48\x57"),                               # 0x15d: mov ebp, 0x57488851
    Instruction(b"\xBE\xCD\x24\xAC\xCF"),                               # 0x162: mov esi, 0xcfac24cd
    Instruction(b"\x01\xF5"),                                           # 0x167: add ebp, esi
    Instruction(b"\x89\xEE"),                                           # 0x169: mov esi, ebp
    Instruction(b"\x89\xD5"),                                           # 0x16b: mov ebp, edx
    Instruction(b"\x41\xBE\xDD\x27\xCA\x42"),                           # 0x16d: mov r14d, 0x42ca27dd
    Instruction(b"\x41\xC1\xCE\x08"),                                   # 0x173: ror r14d, 8
    Instruction(b"\x41\x56"),                                           # 0x177: push r14
    Instruction(b"\x44\x89\xF5"),                                       # 0x179: mov ebp, r14d
    Instruction(b"\x41\x81\xF6\xED\x0B\x12\xDC"),                       # 0x17c: xor r14d, 0xdc120bed
    Instruction(b"\x44\x31\xF5"),                                       # 0x183: xor ebp, r14d
    Instruction(b"\x81\xF6\x6F\x7C\x81\xA8"),                           # 0x186: xor esi, 0xa8817c6f
    Instruction(b"\x21\xEE"),                                           # 0x18c: and esi, ebp
    Instruction(b"\xC1\xC5\x19"),                                       # 0x18e: rol ebp, 0x19
    Instruction(b"\x81\xDD\xAE\xAA\x8C\x8C"),                           # 0x191: sbb ebp, 0x8c8caaae
    Instruction(b"\xBB\xDD\x4A\x97\x4E"),                               # 0x197: mov ebx, 0x4e974add
    Instruction(b"\x41\x5E"),                                           # 0x19c: pop r14
    Instruction(b"\x19\xF5"),                                           # 0x19e: sbb ebp, esi
    Instruction(b"\x81\xCD\x6E\xD6\x14\x58"),                           # 0x1a0: or ebp, 0x5814d66e
    Instruction(b"\x48\x63\xDB"),                                       # 0x1a6: movsxd rbx, ebx
    Instruction(b"\x48\xC1\xDB\x11"),                                   # 0x1a9: rcr rbx, 0x11
    Instruction(b"\x89\xDB"),                                           # 0x1ad: mov ebx, ebx
    Instruction(b"\xC1\xC3\x1C"),                                       # 0x1af: rol ebx, 0x1c
    Instruction(b"\x44\x21\xF3"),                                       # 0x1b2: and ebx, r14d
    Instruction(b"\x48\x8B\x34\x24"),                                   # 0x1b5: mov rsi, qword ptr [rsp]
    Instruction(b"\x48\x8D\x64\x24\x08"),                               # 0x1b9: lea rsp, [rsp + 8]
    Instruction(b"\x5D"),                                               # 0x1be: pop rbp
    Instruction(b"\x41\x11\xDE"),                                       # 0x1bf: adc r14d, ebx
    Instruction(b"\xFF\xC3"),                                           # 0x1c2: inc ebx
    Instruction(b"\x4C\x8B\x34\x24"),                                   # 0x1c4: mov r14, qword ptr [rsp]
    Instruction(b"\x48\x83\xC4\x08"),                                   # 0x1c8: add rsp, 8
    Instruction(b"\x5B"),                                               # 0x1cc: pop rbx
    Instruction(b"\x4C\x89\x1C\x24"),                                   # 0x1cd: mov qword ptr [rsp], r11
    Instruction(b"\x41\x51"),                                           # 0x1d1: push r9
    Instruction(b"\x41\x57"),                                           # 0x1d3: push r15
    Instruction(b"\x66\x45\x89\xD3"),                                   # 0x1d5: mov r11w, r10w
    Instruction(b"\x66\x45\x89\xD7"),                                   # 0x1d9: mov r15w, r10w
    Instruction(b"\x66\x41\x21\xC2"),                                   # 0x1dd: and r10w, ax
    Instruction(b"\x66\x41\x31\xC7"),                                   # 0x1e1: xor r15w, ax
    Instruction(b"\x66\x45\x01\xFA"),                                   # 0x1e5: add r10w, r15w
    Instruction(b"\x41\x5F"),                                           # 0x1e9: pop r15
    Instruction(b"\x50"),                                               # 0x1eb: push rax
    Instruction(b"\x48\x8D\x64\x24\xF8"),                               # 0x1ec: lea rsp, [rsp - 8]
    Instruction(b"\x4C\x89\x14\x24"),                                   # 0x1f1: mov qword ptr [rsp], r10
    Instruction(b"\x52"),                                               # 0x1f5: push rdx
    Instruction(b"\x45\x31\xD2"),                                       # 0x1f6: xor r10d, r10d
    Instruction(b"\x41\x81\xC2\x6A\xD4\x32\x74"),                       # 0x1f9: add r10d, 0x7432d46a
    Instruction(b"\xB8\x13\x5F\xE4\xD4"),                               # 0x200: mov eax, 0xd4e45f13
    Instruction(b"\x41\x81\xEA\xF6\x18\x7A\x85"),                       # 0x205: sub r10d, 0x857a18f6
    Instruction(b"\x44\x01\xD0"),                                       # 0x20c: add eax, r10d
    Instruction(b"\x53"),                                               # 0x20f: push rbx
    Instruction(b"\x15\xFA\x6A\x96\xE3"),                               # 0x210: adc eax, 0xe3966afa
    Instruction(b"\x48\x8D\x15\x6C\xE6\x33\xF7"),                       # 0x215: lea rdx, [rip - 0x8cc1994]
    Instruction(b"\x29\xD2"),                                           # 0x21c: sub edx, edx
    Instruction(b"\x44\x09\xD2"),                                       # 0x21e: or edx, r10d
    Instruction(b"\x49\x81\xDA\xF3\xFF\xFF\xFF"),                       # 0x221: sbb r10, -0xd
    Instruction(b"\x41\x89\xDA"),                                       # 0x228: mov r10d, ebx
    Instruction(b"\x66\x45\x89\xD9"),                                   # 0x22b: mov r9w, r11w
    Instruction(b"\xF7\xDB"),                                           # 0x22f: neg ebx
    Instruction(b"\x81\xEB\x70\xAA\xFB\x93"),                           # 0x231: sub ebx, 0x93fbaa70
    Instruction(b"\x41\x01\xDA"),                                       # 0x237: add r10d, ebx
    Instruction(b"\x5B"),                                               # 0x23a: pop rbx
    Instruction(b"\x41\x09\xD2"),                                       # 0x23b: or r10d, edx
    Instruction(b"\x48\x8D\x15\x53\xE1\x33\xF7"),                       # 0x23e: lea rdx, [rip - 0x8cc1ead]
    Instruction(b"\x48\x8B\x14\x24"),                                   # 0x245: mov rdx, qword ptr [rsp]
    Instruction(b"\x41\x21\xC2"),                                       # 0x249: and r10d, eax
    Instruction(b"\x48\x8D\x64\x24\x08"),                               # 0x24c: lea rsp, [rsp + 8]
    Instruction(b"\x48\x98"),                                           # 0x251: cdqe
    Instruction(b"\x4C\x8B\x14\x24"),                                   # 0x253: mov r10, qword ptr [rsp]
    Instruction(b"\x48\x8D\x64\x24\x08"),                               # 0x257: lea rsp, [rsp + 8]
    Instruction(b"\x48\x8B\x04\x24"),                                   # 0x25c: mov rax, qword ptr [rsp]
    Instruction(b"\x66\x41\x09\xC3"),                                   # 0x260: or r11w, ax
    Instruction(b"\x66\x41\x31\xC1"),                                   # 0x264: xor r9w, ax
    Instruction(b"\x66\x45\x29\xCB"),                                   # 0x268: sub r11w, r9w
    Instruction(b"\x66\x41\x01\xC2"),                                   # 0x26c: add r10w, ax
    Instruction(b"\x66\x44\x01\xD8"),                                   # 0x270: add ax, r11w
    Instruction(b"\x48\x83\xC4\x08"),                                   # 0x274: add rsp, 8
    Instruction(b"\x66\x41\x29\xC2"),                                   # 0x278: sub r10w, ax
    Instruction(b"\x41\x59"),                                           # 0x27c: pop r9
    Instruction(b"\x4C\x8B\x1C\x24"),                                   # 0x27e: mov r11, qword ptr [rsp]
    Instruction(b"\x48\x8D\x64\x24\x08"),                               # 0x282: lea rsp, [rsp + 8]
    Instruction(b"\x8B\x05\xF7\x6E\x33\xF7"),                           # 0x287: mov eax, dword ptr [rip - 0x8cc9109]
    Instruction(b"\x48\x83\xEC\x08"),                                   # 0x28d: sub rsp, 8
    Instruction(b"\x48\x89\x1C\x24"),                                   # 0x291: mov qword ptr [rsp], rbx
    Instruction(b"\x48\x31\xC0"),                                       # 0x295: xor rax, rax
    Instruction(b"\x48\x89\xC3"),                                       # 0x298: mov rbx, rax
    Instruction(b"\x48\x21\xD3"),                                       # 0x29b: and rbx, rdx
    Instruction(b"\x48\x09\xD0"),                                       # 0x29e: or rax, rdx
    Instruction(b"\x48\x89\xDA"),                                       # 0x2a1: mov rdx, rbx
    Instruction(b"\x48\x89\xC3"),                                       # 0x2a4: mov rbx, rax
    Instruction(b"\x48\x29\xD0"),                                       # 0x2a7: sub rax, rdx
    Instruction(b"\x48\x8D\x50\x02"),                                   # 0x2aa: lea rdx, [rax + 2]
    Instruction(b"\x48\xC7\xC0\x00\x00\x00\x00"),                       # 0x2ae: mov rax, 0
    Instruction(b"\x4A\x8D\x04\x90"),                                   # 0x2b5: lea rax, [rax + r10*4]
    Instruction(b"\x45\x31\xD2"),                                       # 0x2b9: xor r10d, r10d
    Instruction(b"\x48\x8B\x1C\x24"),                                   # 0x2bc: mov rbx, qword ptr [rsp]
    Instruction(b"\x49\x89\xDA"),                                       # 0x2c0: mov r10, rbx
    Instruction(b"\x49\xF7\xDA"),                                       # 0x2c3: neg r10
    Instruction(b"\x49\x29\xC2"),                                       # 0x2c6: sub r10, rax
    Instruction(b"\x48\xC7\xC0\x00\x00\x00\x00"),                       # 0x2c9: mov rax, 0
    Instruction(b"\x48\x83\xC4\x08"),                                   # 0x2d0: add rsp, 8
    Instruction(b"\x4C\x29\xD0"),                                       # 0x2d4: sub rax, r10
    Instruction(b"\x44\x8B\x10"),                                       # 0x2d7: mov r10d, dword ptr [rax]
    Instruction(b"\x41\x53"),                                           # 0x2da: push r11
    Instruction(b"\x49\x89\xE3"),                                       # 0x2dc: mov r11, rsp
    Instruction(b"\x9C"),                                               # 0x2df: pushfq
    Instruction(b"\x49\x83\xC3\x00"),                                   # 0x2e0: add r11, 0
    Instruction(b"\x9D"),                                               # 0x2e4: popfq
    Instruction(b"\x4C\x87\x1C\x24"),                                   # 0x2e5: xchg qword ptr [rsp], r11
    Instruction(b"\x5C"),                                               # 0x2e9: pop rsp
    Instruction(b"\x48\x8D\x05\xE9\x35\x96\xFE"),                       # 0x2ea: lea rax, [rip - 0x169ca17]
    Instruction(b"\x48\x89\x04\x24"),                                   # 0x2f1: mov qword ptr [rsp], rax
    Instruction(b"\x8B\x05\xE4\xD6\x35\xFD"),                           # 0x2f5: mov eax, dword ptr [rip - 0x2ca291c]
    Instruction(b"\x48\xC1\xE0\x20"),                                   # 0x2fb: shl rax, 0x20
    Instruction(b"\x53"),                                               # 0x2ff: push rbx
    Instruction(b"\x48\xF7\xDB"),                                       # 0x300: neg rbx
    Instruction(b"\x48\x8D\x1D\x6E\xEB\x95\xF9"),                       # 0x303: lea rbx, [rip - 0x66a1492]
    Instruction(b"\x5B"),                                               # 0x30a: pop rbx
    Instruction(b"\x48\xC1\xF8\x20"),                                   # 0x30b: sar rax, 0x20
    Instruction(b"\x48\x01\x04\x24"),                                   # 0x30f: add qword ptr [rsp], rax
    Instruction(b"\x48\x8D\x05\xD4\x8C\x93\xFA"),                       # 0x313: lea rax, [rip - 0x56c732c]
    Instruction(b"\x48\x8D\x64\x24\xF8"),                               # 0x31a: lea rsp, [rsp - 8]
    Instruction(b"\x4C\x89\x2C\x24"),                                   # 0x31f: mov qword ptr [rsp], r13
    Instruction(b"\x4D\x31\xED"),                                       # 0x323: xor r13, r13
    Instruction(b"\x52"),                                               # 0x326: push rdx
    Instruction(b"\x49\x31\xC5"),                                       # 0x327: xor r13, rax
    Instruction(b"\xFF\xC8"),                                           # 0x32a: dec eax
    Instruction(b"\x41\x52"),                                           # 0x32c: push r10
    Instruction(b"\x4C\x89\xD0"),                                       # 0x32e: mov rax, r10
    Instruction(b"\x48\xBA\x00\x00\x00\x00\x01\x00\x00\x00"),           # 0x331: movabs rdx, 0x100000000
    Instruction(b"\x48\xF7\xE2"),                                       # 0x33b: mul rdx
    Instruction(b"\x48\x8D\x15\x85\x17\xCB\xFD"),                       # 0x33e: lea rdx, [rip - 0x234e87b]
    Instruction(b"\x49\x89\xD2"),                                       # 0x345: mov r10, rdx
    Instruction(b"\x0F\xBA\xEA\x18"),                                   # 0x348: bts edx, 0x18
    Instruction(b"\x4C\x87\x14\x24"),                                   # 0x34c: xchg qword ptr [rsp], r10
    Instruction(b"\x48\x83\xC4\x08"),                                   # 0x350: add rsp, 8
    Instruction(b"\x49\x89\xC2"),                                       # 0x354: mov r10, rax
    Instruction(b"\x48\x8B\x14\x24"),                                   # 0x357: mov rdx, qword ptr [rsp]
    Instruction(b"\x48\x0F\xAB\xF8"),                                   # 0x35b: bts rax, rdi
    Instruction(b"\x49\xC1\xFA\x20"),                                   # 0x35f: sar r10, 0x20
    Instruction(b"\x0F\xBA\xE8\x0D"),                                   # 0x363: bts eax, 0xd
    Instruction(b"\x48\x83\xC4\x08"),                                   # 0x367: add rsp, 8
    Instruction(b"\x4C\x87\x2C\x24"),                                   # 0x36b: xchg qword ptr [rsp], r13
    Instruction(b"\x48\x83\xC4\x08"),                                   # 0x36f: add rsp, 8
    Instruction(b"\x48\x8D\x04\x24"),                                   # 0x373: lea rax, [rsp]
    Instruction(b"\x48\x8B\x00"),                                       # 0x377: mov rax, qword ptr [rax]
    Instruction(b"\x48\x89\x3C\x24"),                                   # 0x37a: mov qword ptr [rsp], rdi
    Instruction(b"\x48\x81\xEF\xC3\xFF\xFF\xFF"),                       # 0x37e: sub rdi, -0x3d
    Instruction(b"\x48\xFF\xCF"),                                       # 0x385: dec rdi
    Instruction(b"\x49\x01\xC2"),                                       # 0x388: add r10, rax
    Instruction(b"\x49\x8D\x3A"),                                       # 0x38b: lea rdi, [r10]
    Instruction(b"\x9C"),                                               # 0x38e: pushfq
    Instruction(b"\x48\x31\x7C\x24\x08"),                               # 0x38f: xor qword ptr [rsp + 8], rdi
    Instruction(b"\x48\x33\x7C\x24\x08"),                               # 0x394: xor rdi, qword ptr [rsp + 8]
    Instruction(b"\x48\x31\x7C\x24\x08"),                               # 0x399: xor qword ptr [rsp + 8], rdi
    Instruction(b"\x9D"),                                               # 0x39e: popfq
    Instruction(b"\xC3")                                                # 0x39f: ret
    # -- end --
])
ctx.processing(block, 0xaaaa000000000000)

rax = ctx.simplify(ctx.getRegisterAst(ctx.registers.rax), llvm=True)
rbx = ctx.simplify(ctx.getRegisterAst(ctx.registers.rbx), llvm=True)
rcx = ctx.simplify(ctx.getRegisterAst(ctx.registers.rcx), llvm=True)
rdx = ctx.simplify(ctx.getRegisterAst(ctx.registers.rdx), llvm=True)
rdi = ctx.simplify(ctx.getRegisterAst(ctx.registers.rdi), llvm=True)
rsi = ctx.simplify(ctx.getRegisterAst(ctx.registers.rsi), llvm=True)
rsp = ctx.simplify(ctx.getRegisterAst(ctx.registers.rsp), llvm=True)
rbp = ctx.simplify(ctx.getRegisterAst(ctx.registers.rbp), llvm=True)
r8  = ctx.simplify(ctx.getRegisterAst(ctx.registers.r8), llvm=True)
r9  = ctx.simplify(ctx.getRegisterAst(ctx.registers.r9), llvm=True)
r10 = ctx.simplify(ctx.getRegisterAst(ctx.registers.r10), llvm=True)
r11 = ctx.simplify(ctx.getRegisterAst(ctx.registers.r11), llvm=True)
r12 = ctx.simplify(ctx.getRegisterAst(ctx.registers.r12), llvm=True)
r13 = ctx.simplify(ctx.getRegisterAst(ctx.registers.r13), llvm=True)
r14 = ctx.simplify(ctx.getRegisterAst(ctx.registers.r14), llvm=True)
r15 = ctx.simplify(ctx.getRegisterAst(ctx.registers.r15), llvm=True)

print()

print(f'rax = {rax}')
print(f'rbx = {rbx}')
print(f'rcx = {rcx}')
print(f'rdx = {rdx}')
print(f'rdi = {rdi}')
print(f'rsi = {rsi}')
print(f'rsp = {rsp}')
print(f'rbp = {rbp}')
print(f'r8 = {r8}')
print(f'r9 = {r9}')
print(f'r10 = {r10}')
print(f'r11 = {r11}')
print(f'r12 = {r12}')
print(f'r13 = {r13}')
print(f'r14 = {r14}')
print(f'r15 = {r15}')
```

**Comment by unknown-re** [comment]
check your twitter dms & delete this Issue
