### ISSUE TITLE
Bug in AST duplication

### ISSUE THREAD

**Issue by werew** [JonathanSalwan/Triton#792]
I would like to make a copy of an AST (so that I can perform edits without modifying the original one) and evaluate it giving different symbolic variables. However when I set the symbolic variables this are concertized correctly in the original AST but not in its copy or unrolled counterpart: 

```python
from triton import *

ctx = TritonContext()
ctx.setArchitecture(ARCH.X86_64)
ac = ctx.getAstContext()

var1 = ctx.newSymbolicVariable(64, 'var1')
var2 = ctx.newSymbolicVariable(64, 'var2')

ast_original  = ac.bvadd(ac.variable(var1), ac.variable(var2))
ast_duplicate = ac.duplicate(ast_original)
ast_unrolled  = ac.unrollAst(ast_original)

ctx.setConcreteVariableValue(var1, 4)
ctx.setConcreteVariableValue(var2, 2)

print('AST ORIGINAL:  {}'.format(ast_original.evaluate()))
print('AST DUPLICATE: {}'.format(ast_duplicate.evaluate()))
print('AST UNROLLED:  {}'.format(ast_unrolled.evaluate()))
```

Output:
```
AST ORIGINAL:  6
AST DUPLICATE: 0
AST UNROLLED:  0
```

Is this a Triton bug or it should be done differently ?

**Comment by JonathanSalwan** [comment]
Thanks for reporting that. I've pushed a patch. Tell me if it's ok for your use case :).

**Comment by werew** [comment]
Thanks for the patch, everything works correctly now :)

**Comment by werew** [comment]
There is still an issue: references are not handled correctly. 
Note the following example, here `ast_unrolled` remains unchanged since all references are missing, however  `ast_original` is modified as a side effect of modifying `st_duplicate`:

```
from triton import *

ctx = TritonContext()
ctx.setArchitecture(ARCH.X86_64)
ac = ctx.getAstContext()

var1 = ctx.newSymbolicVariable(64, 'var1')
var2 = ctx.newSymbolicVariable(64, 'var2')
var3 = ctx.newSymbolicVariable(64, 'var3')

var1_node = ac.variable(var1)
var2_node = ac.variable(var2)
var3_node = ac.variable(var3)

sym_expr= ctx.newSymbolicExpression(ac.bvadd(var1_node, var2_node),'my symexpr')

ast_original  = ac.bvmul(ac.reference(sym_expr), var1_node)
ast_duplicate = ac.duplicate(ast_original)
ast_unrolled  = ac.unrollAst(ast_original)

def substitute_all_ast_instances(ast, target_ast, replacement_ast):
    """NOTE: REFERENCE nodes are ignored """

    while ast.getType() == AST_NODE.REFERENCE:
        ast = ast.getSymbolicExpression().getAst()

    if ast.equalTo(target_ast):
        return replacement_ast

    for idx, child in enumerate(ast.getChildren()):
        ast.setChild(idx, substitute_all_ast_instances(child, target_ast, replacement_ast))

    return ast

ast = substitute_all_ast_instances(ast_duplicate, var1_node, var3_node)

print(ac.lookingForNodes(ast_original, AST_NODE.VARIABLE))
print(ac.lookingForNodes(ast_duplicate, AST_NODE.VARIABLE))
print(ac.lookingForNodes(ast_unrolled, AST_NODE.VARIABLE))

print(ac.unrollAst(ast_original))
print(ac.unrollAst(ast_duplicate))
print(ac.unrollAst(ast_unrolled))
```
OUTPUT:
```
[SymVar_2, SymVar_1, SymVar_0]
[SymVar_1, SymVar_2]
[SymVar_1, SymVar_0]
(bvmul (bvadd SymVar_2 SymVar_1) SymVar_0)
(bvmul (bvadd SymVar_2 SymVar_1) SymVar_2)
(bvmul (bvadd SymVar_0 SymVar_1) SymVar_0)
```

**Comment by werew** [comment]
Maybe I know what is the issue. 
The reference node is duplicated correclty: https://github.com/JonathanSalwan/Triton/blob/b7671c3e5259b321e7faf8c6ed1a5d8bf1e75f90/src/libtriton/ast/ast.cpp#L2454-L2460

However traversing its children has no effect since a reference node has no children, but we should rather `ReferenceNode->getSymbolicExpression()->getAst()`:
https://github.com/JonathanSalwan/Triton/blob/b7671c3e5259b321e7faf8c6ed1a5d8bf1e75f90/src/libtriton/ast/ast.cpp#L2475-L2480
